### ISSUE TITLE
Unrecognized Words

### ISSUE THREAD

**Issue by xotmatrix** [a2-4am/million-perfect-letters#1]
4am:
> If you make words that you feel should match (that aren't obviously obscene) but the game doesn't recognize them, please let me know

Please check if they have been reported or fixed and submit your missing words here.

**Comment by xotmatrix** [comment]
Four Letter Words

common: 
bail, bore, brie, celt, chin, chit, dews, duly, fest, gazy, hail, leek, mosh, nave, pell, phat, roes, serf, smut, taro, tern, tish, tout, vert, wort

informal: 
cine, tris, unis, lase, pols

archaic/historic: 
carn, dern, fals, falt, fets, floo, hins, lave, lese, meak, rown, thee, tole, tope, vail, wert, wode, wold

regional/dialectical: 
carn, dern, fash, lear, leed, tarn, tole, tosh, wald

possibly offensive: 
berk

proper nouns: 
baal, bart, chet, july

**Comment by ivanizag** [comment]
I missed "luge" and "fats".

**Comment by roughana** [comment]
crumple, reargue
