### ISSUE TITLE
Escape key behavior

### ISSUE THREAD

**Issue by antoinevignau** [a2-4am/million-perfect-letters#2]
When playing, pressing ESC directly goes to the main menu. Could there be 1/ a quit confirmation and then 2/ go to the puzzle selection menu instead of the main menu (ie. go back one level, not two)?

**Comment by a2-4am** [comment]
No quit confirmation, but Esc during play now returns to selection menu. https://github.com/a2-4am/million-perfect-letters/commit/905b567ee1440a00a6ee3b5d7fb2e79928b9044d
